# Generated by Django 4.2.2 on 2023-06-17 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "verbose_name": "Часто Задаваемый Вопрос",
                "verbose_name_plural": "Часто Задаваемые Вопросы",
            },
        ),
    ]
