# Generated by Django 4.2.2 on 2023-06-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, verbose_name='Регион/Область')),
                ('adress', models.CharField(max_length=255, verbose_name='Адресс')),
            ],
        ),
        migrations.AddField(
            model_name='formforuser',
            name='adress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FormForUsers', to='tests.adress', verbose_name='Адресс'),
            preserve_default=False,
        ),
    ]
