# Generated by Django 4.2.2 on 2023-06-18 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0002_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='tests.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='OfflineRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_selection', models.DateTimeField(verbose_name='Выбор даты и времени')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Утверждено')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.adress', verbose_name='Адрес')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на запись на офлайн',
                'verbose_name_plural': 'Заявки на запись на офлайн',
            },
        ),
    ]
