# Generated by Django 4.2.2 on 2023-06-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_adress_options_formforuser_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforuser',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FormForUsers', to='tests.adress', verbose_name='Адресс'),
        ),
    ]
